"""IOIntelligenceLLM implementation for LangChain."""

import os
from typing import Any, Dict, List, Optional, cast

from dotenv import load_dotenv
from langchain_core.exceptions import OutputParserException as GenerationError
from langchain_core.language_models.llms import LLM

from .exceptions import IOIntelligenceError
from .http_client import IOIntelligenceHTTPClient

# Load environment variables from .env file
load_dotenv()


class IOIntelligenceLLM(LLM):
    """LangChain LLM wrapper for io Intelligence API.

    This is the text-in/text-out interface. For image input (vision models)
    use :class:`~langchain_iointelligence.IOIntelligenceChatModel` together
    with :func:`~langchain_iointelligence.vision_message`.

    As of 0.6.0, requests are routed through :class:`IOIntelligenceHTTPClient`
    which adds exponential-backoff retries and classified exception types
    (all subclasses of ``GenerationError`` for backward compatibility).
    """

    # Declare all fields that will be used
    io_api_key: str = ""
    io_api_url: str = ""
    model: str = "meta-llama/Llama-3.3-70B-Instruct"
    max_tokens: int = 1000
    temperature: float = 0.7
    timeout: int = 30
    max_retries: int = 3
    retry_delay: float = 1.0

    def __init__(self, api_key: Optional[str] = None, api_url: Optional[str] = None, **kwargs):
        """Initialize IOIntelligenceLLM.

        Args:
            api_key: io Intelligence API key (optional, defaults to IO_API_KEY env var)
            api_url: io Intelligence API URL (optional, defaults to IO_API_URL env var)
            model: Model name to use (default: "meta-llama/Llama-3.3-70B-Instruct")
            max_tokens: Maximum tokens to generate (default: 1000)
            temperature: Temperature for generation (default: 0.7)
            timeout: Request timeout in seconds (default: 30)
            max_retries: Maximum number of retries (default: 3)
            retry_delay: Initial retry delay in seconds (default: 1.0)
        """
        # Extract and set API credentials
        api_key = api_key or os.getenv("IO_API_KEY")
        api_url = api_url or os.getenv("IO_API_URL")

        if not api_key:
            raise ValueError(
                "IO_API_KEY must be provided either as parameter or environment variable"
            )
        if not api_url:
            raise ValueError(
                "IO_API_URL must be provided either as parameter or environment variable"
            )

        # Set field values explicitly
        kwargs["io_api_key"] = api_key
        kwargs["io_api_url"] = api_url

        super().__init__(**kwargs)

        self._http_client: Optional[Any] = None

    @property
    def _llm_type(self) -> str:
        """Return identifier of LLM type."""
        return "io_intelligence"

    @property
    def http_client(self):
        """Get or create HTTP client."""
        if self._http_client is None:
            self._http_client = IOIntelligenceHTTPClient(
                api_key=self.io_api_key,
                api_url=self.io_api_url,
                timeout=self.timeout,
                max_retries=self.max_retries,
                retry_delay=self.retry_delay,
            )
        return self._http_client

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[Any] = None,
        **kwargs: Any,
    ) -> str:
        """Run the LLM on the given prompt and input.

        Args:
            prompt: The prompt to pass into the model.
            stop: Optional list of stop words to use when generating.
            run_manager: Optional callback manager.
            **kwargs: Additional keyword arguments.

        Returns:
            The string generated by the model.

        Raises:
            GenerationError: If the API request fails.
        """
        # io Intelligence API uses OpenAI-compatible format
        data: Dict[str, Any] = {
            "model": self.model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
        }

        # Add stop words if provided
        if stop:
            data["stop"] = stop

        # Add any additional kwargs
        data.update(kwargs)

        try:
            response_data = self.http_client.post_with_retry(data)

            if "choices" not in response_data or not response_data["choices"]:
                raise GenerationError("No choices in API response")

            choice = response_data["choices"][0]

            # Chat format: choices[0].message.content
            if "message" in choice and "content" in choice["message"]:
                return cast(str, choice["message"]["content"])

            # Completion format: choices[0].text
            if "text" in choice:
                return cast(str, choice["text"])

            raise GenerationError(
                "Unsupported response schema - expected 'message.content' or 'text' in choices"
            )

        except IOIntelligenceError:
            raise
        except (KeyError, IndexError) as e:
            raise GenerationError(f"Invalid API response format: {str(e)}")

    @property
    def _identifying_params(self) -> Dict[str, Any]:
        """Return a dictionary of identifying parameters."""
        return {
            "model": self.model,
            "max_tokens": self.max_tokens,
            "temperature": self.temperature,
        }
