name: Minimal Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Quick lint check (critical errors only)
      run: |
        flake8 langchain_iointelligence/ --select=E9,F63,F7,F82 --show-source
    
    - name: Run tests
      env:
        IO_API_KEY: test_api_key_for_github_actions
        IO_API_URL: https://test.example.com/v1/chat/completions
      run: |
        pytest tests/test_llm.py tests/test_chat.py -v
